spring.application.name=smms

spring.datasource.url=jdbc:mysql://localhost:3306/smms

spring.datasource.username=Shaheer
spring.datasource.password=Shaheer1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true